version: "3.9"

services:
  nginx:
    build: ./src/nginx
    container_name: nginx-frontend
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf 

  php:
    build: ./src/php
    container_name: php-backend
    networks:
      - app-network
    environment:
      DB_HOST: mysql-db
      DB_USER: DB_USER 
      DB_PASSWORD: Pass@123
      DB_NAME: mydatabase

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
      MYSQL_DATABASE: mydatabase
    networks:
      - app-network
    volumes:
      - ./src/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

networks:
  app-network:

volumes:
  mysql-data: