version: "3.9"

services:
  nginx:
    build: ./src/nginx
    container_name: nginx-frontend
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: ./src/php
    container_name: php-backend
    networks:
      - app-network

  mysql:
    build: ./src/mysql
    container_name: mysql-db
    networks:
      - app-network

networks:
  app-network:
